"""files.content mediumtext

Revision ID: b23f1fe6c198
Revises: 587cd9ad3541
Create Date: 2022-01-24 10:36:43.380754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b23f1fe6c198'
down_revision = '587cd9ad3541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_bin'),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'content',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.TEXT(collation='utf8mb4_bin'),
               existing_nullable=True)
    # ### end Alembic commands ###
